### ISSUE TITLE
birdsitelive exited with code 1

### ISSUE THREAD

**Issue by masukomi** [NicolasConstant/BirdsiteLive#164]
```
standard_init_linux.go:219: exec user process caused: exec format error
```

getting a ton of these when running `docker-compose up` after following [the instructions here](https://github.com/NicolasConstant/BirdsiteLive/blob/master/INSTALLATION.md).

like 9 in a row followed by `birdsitelive exited with code 1`

**Comment by NicolasConstant** [comment]
If you do `docker-compose up` instead of `docker-compose up -d` as described in the docs, do you have a bit more info?

**Comment by oaklandm** [comment]
I have this issue also when setting up using Portainer. I haven't figured out how to get detailed logs from Portainer yet but these are the events I get..
Container birdsitelive started
Container birdsitelive exited with status code 1
Container disconnected from birdsitelive_birdsitelivenetwork network

**Comment by NicolasConstant** [comment]
Is it possible you're trying to run it on another CPU architecture than amd64? (arm?)

**Comment by NicolasConstant** [comment]
Raspberry Pi has an Arm based CPU, so that's normal that it doesn't work with the official docker image (limited to amd64 currently).

**Comment by oaklandm** [comment]
Oh sorry, may bad, I completely misunderstood.

**Comment by masukomi** [comment]
pretty sure i was running it on pi. Figured it was fine since so many things want you to run docker images on pi. :/ 

So, I guess maybe the right "fix" here is to just add a note to the README that the docker image doesn't work on Pi or ARM macs.

**Comment by NicolasConstant** [comment]
I've updated the README accordingly. 🙂

**Comment by felixmueller** [comment]
Hi @masukomi and @NicolasConstant,

I successfully managed to run the latest unmodified Docker image of BSL on ARM (aarch64) by using Docker's built in multi arch support using qemu.

The CPU I am using is from the same family as the Raspberry Pi, so it should run on Raspberry Pi as well! Performance is not an issue in my case, but I'm running a small private instance only.

I had to extend my docker-compose.yml to specify the platform architecture and to make sure that amd64 support is enabled before running the BSL container as follows:

```
version: "3"

networks:
    birdsitelivenetwork:
        external: false

services:
    server:
        platform: linux/amd64
        image: nicolasconstant/birdsitelive:latest
        restart: always
        container_name: birdsitelive
        environment:
            - Instance:Domain=domain.name
            - Instance:AdminEmail=name@domain.ext
            - Db:Type=postgres
            - Db:Host=db
            - Db:Name=birdsitelive
            - Db:User=birdsitelive
            - Db:Password=birdsitelive
            - Twitter:ConsumerKey=twitter.api.key
            - Twitter:ConsumerSecret=twitter.api.key
        networks:
            - birdsitelivenetwork
        ports:
            - "5000:80"
        depends_on:
            - amd64
            - db

    amd64:
        image: tonistiigi/binfmt
        restart: on-failure
        container_name: amd64
        privileged: true
        command:
            - --install
            - amd64

    db:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=birdsitelive
            - POSTGRES_PASSWORD=birdsitelive
            - POSTGRES_DB=birdsitelive
        networks:
            - birdsitelivenetwork
        volumes:
            - ./postgres:/var/lib/postgresql/data
```
