### ISSUE TITLE
The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.

### ISSUE THREAD

**Issue by gregology** [NicolasConstant/BirdsiteLive#166]
I'm getting this error when I `$ docker-compose up`
```
birdsitelive | Unhandled exception. System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
birdsitelive |    at System.IO.FileSystemWatcher.StartRaisingEvents()
birdsitelive |    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
birdsitelive |    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
birdsitelive |    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
birdsitelive |    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
birdsitelive |    at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
birdsitelive |    at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
birdsitelive |    at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
birdsitelive |    at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
birdsitelive |    at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
birdsitelive |    at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
birdsitelive |    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
birdsitelive |    at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
birdsitelive |    at Microsoft.Extensions.Hosting.HostBuilder.Build()
birdsitelive |    at BirdsiteLive.Program.Main(String[] args) in /src/BirdsiteLive/Program.cs:line 19
birdsitelive exited with code 139
```

I am using the comsumerkey and consumersecret from a Twitter standalone app I created.

this is my redacted `docker-compose.yml`
```
version: "3"

networks:
    birdsitelivenetwork:
        external: false

services:
    server:
        image: nicolasconstant/birdsitelive:latest
        restart: always
        container_name: birdsitelive
        environment:
            - Instance:Domain=birdsite.url
            - Instance:greg@email.com
            - Db:Type=postgres
            - Db:Host=db
            - Db:Name=birdsitelive
            - Db:User=birdsitelive
            - Db:Password=birdsitelive
            - Twitter:ConsumerKey=foo
            - Twitter:ConsumerSecret=bar
        networks:
            - birdsitelivenetwork
        ports:
            - "6000:80"
        depends_on:
            - db

    db:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=birdsitelive
            - POSTGRES_PASSWORD=birdsitelive
            - POSTGRES_DB=birdsitelive
        networks:
            - birdsitelivenetwork
        volumes:
            - /home/user/birdsitelive/postgres:/var/lib/postgresql/data
```

any ideas for trouble shooting?
